version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pipenv run python -m pytest --cov=slackstorian --duration=5
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: echo "test deploy"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy
