version: 2
orbs:
  aws-cli: circleci/aws-cli@0.1.13

commands:
  deploy-lambda:
    description: "Deploys a zip file"
    parameters:
      function-name:
        type: string
      function-handler:
        type: string
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ID_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION
      - run:
          name: Deploy new lambda
          cmd: |
              aws lambda update-function-code --region $AWS_REGION --function-name "<< parameters.function-name >>" --zip-file ./build.zip --query "LastModified"
              aws lambda update-function-configuration --region $AWS_REGION --function-name "lunchRota" --handler "<< parameters.function-handler >>" --query "Handler"
  build-release:
    description: "Makes a zip file from project"
    steps:
      - checkout
      - run:
          name: Create directory
          cmd: mkdir build
      - run:
          name: Copy souce package
          cmd: cp -r ./slackstorian ./build
      - run:
          name: Package dependencies
          cmd: |
            pipenv lock -r > requirements.txt
            pipenv run pip install -r requirements.txt --no-deps -t build
      - run:
          name: Create zip
          cmd: zip build.zip ./build/**
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pipenv run python -m pytest --cov=slackstorian --duration=5
  deploy-production:
    docker:
      - image: circleci/python:3.7
    steps:
      - build-release
      - deploy-lambda:
          function-name:    'slackstorian-production'
          function-handler: 'slackstorian.main'
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - deploy-production:
          requires:
            - test

