version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13

commands:
  deploy-lambda:
    description: "Deploys a zip file"
    parameters:
      function-name:
        type: string
      function-handler:
        type: string
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ID_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION
      - run:
          name: Deploy new lambda
          command: |
            aws lambda update-function-code --region $AWS_REGION --function-name "<< parameters.function-name >>" --zip-file "fileb://$CIRCLE_WORKING_DIRECTORY/build.zip" --query "LastModified"
            aws lambda update-function-configuration --region $AWS_REGION --function-name "<< parameters.function-name >>" --handler "<< parameters.function-handler >>" --query "Handler"
  build-release-zip:
    description: "Makes a zip file from project"
    steps:
      - run:
          name: Package dependencies
          command: |
            pipenv lock -r > requirements.txt
            pipenv run pip install -r requirements.txt --no-deps -t slackstorian
      - run:
          name: Create zip
          command: |
            cd slackstorian
            zip -r slackstorian.zip *
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pipenv sync --dev
      - run: pipenv run python -m pytest --cov=slackstorian --duration=5
  deploy-production:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - build-release-zip
      - deploy-lambda:
          function-name:    'arn:aws:lambda:eu-west-2:559789578064:function:slackstorian-production'
          function-handler: '__init__.main'
workflows:
  ci:
    jobs:
      - test
      - deploy-production:
          requires:
            - test
          filters:
            branches:
              only: master

